### ISSUE TITLE
RefreshLayout 为根布局时，headerView设置无效

### ISSUE THREAD

**Issue by wyh497823256** [genius158/PullRefreshLayout#1]

**Comment by wyh497823256** [comment]
#BUG

**Comment by genius158** [comment]
demo里的布局已经改为
<com.yan.pullrefreshlayout.PullRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/refreshLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</com.yan.pullrefreshlayout.PullRefreshLayout>
并没有出现你说的问题，可能你加载更多后 没有调用loadMoreComplete()

**Comment by wyh497823256** [comment]
@genius158 我已经禁用了加载更多，并且代码在没做任何修改的情况下，加了一个父控件上去，显示正常

**Comment by genius158** [comment]
@wyh497823256 demo 默认就是 禁用加载更多的 呀 没有 问题呀。
设置的 代码 发一下

**Comment by wyh497823256** [comment]
fragment_life_srl = (PullRefreshLayout) view.findViewById(R.id.fragment_life_srl);
        fragment_life_srl.setHeaderView(new RefreshViewHeader(getContext()));

        fragment_life_srl.setOnRefreshListener(new PullRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh() {
                loadData();
            }
        });

**Comment by genius158** [comment]
@wyh497823256 RefreshViewHeader 实现 PullRefreshLayout.OnPullListener 了 没有？

**Comment by wyh497823256** [comment]
@genius158  这个没有实现。
