### ISSUE TITLE
PullRefreshLayout里面放置Listview后使用ClassicHoldLoadView可以实现自动加载更多吗？貌似里面只有NestedScrollView和RecyclerView？ 求教一下

### ISSUE THREAD

**Issue by yulongxiao** [genius158/PullRefreshLayout#14]
private void scrollInit() {
        post(new Runnable() {
            @Override
            public void run() {
                final View target = refreshLayout.getTargetView();
                refreshLayout.setLoadTriggerDistance(tv.getHeight());
                target.setOverScrollMode(OVER_SCROLL_NEVER);
                ((ViewGroup) target).setClipToPadding(false);

                if (target instanceof NestedScrollView) {
                    ((NestedScrollView) target).setOnScrollChangeListener(new NestedScrollView.OnScrollChangeListener() {
                        @Override
                        public void onScrollChange(NestedScrollView v, int scrollX, int scrollY, int oldScrollX, int oldScrollY) {
                            if (refreshLayout.isRefreshing()) {
                                return;
                            }
                            setTargetTranslationY();
                        }
                    });
                }
                else if (target instanceof RecyclerView) {
                    ((RecyclerView) target).addOnScrollListener(new RecyclerView.OnScrollListener() {
                        @Override
                        public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                            if (refreshLayout.isRefreshing()) {
                                return;
                            }
                            setTargetTranslationY();
                        }
                    });
                }

                setTargetTranslationY();
            }
        });
    }

**Comment by genius158** [comment]
@yulongxiao demo没有做listView的适配，不过做法都差不多，
本身listView用的太少了，就没有对它做适配。

**Comment by yulongxiao** [comment]
我试着做了下，在最后加载完成悬停跟随划动那里达不到预想的效果，大神后期能否加上listview的实现呢？

**Comment by genius158** [comment]
@yulongxiao 啊~ 现在再老的项目应该也改用recyclerView了吧~
