### ISSUE TITLE
你好，关于demo中仿支付宝的刷新效果，有个问题想请教一下

### ISSUE THREAD

**Issue by AndroidRubin** [genius158/PullRefreshLayout#15]
我仿照demo自己写了一个页面，但是有一个问题，当我的header部分是一个listview的情况时（listview高度会自适应，重写了onMeasure），而我的listview是从网络中获取得数据，那么这种情况下，我的内容区域会飘在header的中间部分，我觉得是没有重新计算header的宽高，请问这部分有解决方法吗，谢谢

**Comment by genius158** [comment]
@AndroidRubin 新提交的demo，DiDiListViewActivity

**Comment by AndroidRubin** [comment]
谢谢~
