### ISSUE TITLE
单纯回弹模块common_activity4.xml   36  38  50 52 行， 这里改一下就丢失回弹效果，是不是跟layout_weight 有关？

### ISSUE THREAD

**Issue by BigCowHere** [genius158/PullRefreshLayout#16]
单纯回弹模块common_activity4.xml 的第  36  38  50 52 行， 这里改一下就就丢失回弹效果，是不是跟layout_weight 有关？
 类似这种
    android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="0.3"
 
            android:id="@+id/refreshLayout2"
            android:overScrollMode="never"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="0.7"

**Comment by genius158** [comment]
没有～
