### ISSUE TITLE
滑动监听如何设置

### ISSUE THREAD

**Issue by NicolasKun** [genius158/PullRefreshLayout#18]
您好 
查看源码并尝试在dellScroll(float distanceY)中监听tempDistance 
发现数据只有在真实滑动时有效  但在控件回弹滑动中并无调用  请问本项目的滑动监听应该如何写?

**Comment by genius158** [comment]
回弹，是在回弹动画那里，为了方便，根据动画的返回的当前值，直接设置的，

**Comment by genius158** [comment]
header和footer都有回调

**Comment by NicolasKun** [comment]
多谢回答
