### ISSUE TITLE
虚假广告

### ISSUE THREAD

**Issue by ghost** [genius158/PullRefreshLayout#2]
你知道满怀期待兴奋，以为真的有人做出来很接近QQ的回弹效果的控件，运行之后，满满的失望的心情吗？你敢再牛B吹的再大点吗？

**Comment by genius158** [comment]
@Jeff518 你说嘛，怎么虚假了，差很多吗？相比主流的回弹刷新控件，效果不好，我才写的这个库

**Comment by genius158** [comment]
@Jeff518 你去看看其他的回弹刷新库，我认为，标题这么写，完全没有问题

**Comment by genius158** [comment]
@Jeff518 还有感谢你提issue，希望你在表达不满的情绪的同时能，把问题写上去，哪里有问题，哪里让你满满的失望了，哪里我敢再把牛B吹大一点，最后由衷的表示感谢

**Comment by genius158** [comment]
@Jeff518 还有感谢你提issue，希望你在表达不满的情绪的同时能，把问题写上去，哪里有问题，哪里让你满满的失望了，哪里我敢再把牛B吹大一点，这样有助于个人的开发改进，
最后由衷的表示感谢

**Comment by ghost** [comment]
@genius158 QQ的下拉时，会越往下拉，感觉越难往下拉，仿弹簧拉的越长，就越难的效果，目前我是采用log函数来实现的，但是感觉还是差了一点点，所以才很注意看看有没有同仁有更好的实现方式。最近看了很多说仿QQ下拉回弹的开源库，都没有做这样的处理，浪费了很多时间，所以心里有些烦躁了！抱歉！！

**Comment by genius158** [comment]
@Jeff518 我的标题也写了是回弹效果接近，至于仿弹簧拉的越长，就越难的效果（这个效果我没加，是因为个人的库下拉方式header有固定的，稍微有点不好处理）
