### ISSUE TITLE
Fragment中使用该刷新控件 

### ISSUE THREAD

**Issue by inshyma** [genius158/PullRefreshLayout#20]
Fragment中使用该刷新控件,内嵌套LinearLayout,  LinearLayout内再嵌套ListView和RelativeLayout
我想使用ListView 的setEmptyView方法将RelativeLayout作为EmptyView 
但是上拉和下拉显示的效果有问题 
然而该布局在Activity使用时没问题(不排除其他可能  只是暂时出现这样的现象)

**Comment by genius158** [comment]
能给个xml么 有空看看

**Comment by inshyma** [comment]
已经邮件发送 请注意接收

**Comment by genius158** [comment]
@inshyma 并没有收到邮件，
按照你的描述的
参考 https://github.com/genius158/PullRefreshLayout/blob/developer/app/src/main/java/com/yan/refreshloadlayouttest/testactivity/NestedActivity.java

**Comment by inshyma** [comment]
我们不一样;我的滑动控件用的是ListView  并且ListView和一个相对布局在同一个父控件内,这个相对布局(声明为 empytView) 在ListView.setEmptyView(emptyView) 测试的时候注意下 有数据时显示ListView 无数据显示EmptyView

**Comment by genius158** [comment]
@inshyma 建议 不要使用setEmptyView , 自己控制状态界面的显示

**Comment by inshyma** [comment]
好吧
