### ISSUE TITLE
感谢楼主提供了这么轻量级的刷新库

### ISSUE THREAD

**Issue by 1371030** [genius158/PullRefreshLayout#21]
开源的刷新库基本都用过，感觉实际上需要的还是个轻量级的，正好找到这个！发现个问题就是，上拉刷新完成时。footer有动画下滑，这个能取消吗？

支付宝那个演示，支付宝刷新高度是固定，演示却没有，能固定吗？

**Comment by genius158** [comment]
第一个问题，参考https://github.com/genius158/PullRefreshLayout/blob/master/app/src/main/java/com/yan/refreshloadlayouttest/testactivity/CommonActivity3.java

二，要固定的话写死就好了呀。
