### ISSUE TITLE
用该布局实现会发现有事件冲突，CoordinatorLayout，是不是没有做事件处理？

### ISSUE THREAD

**Issue by PossibleZero** [genius158/PullRefreshLayout#23]
实现不了悬停效果。
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <LinearLayout
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="#30469b"
        android:orientation="vertical"></LinearLayout>

    <com.yan.pullrefreshlayout.PullRefreshLayout
        android:id="@+id/parl"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <android.support.design.widget.CoordinatorLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            tools:context=".frame.tabactivity.CoordinatorActivity">

            <android.support.design.widget.AppBarLayout
                android:id="@+id/appbarlayout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:theme="@style/AppTheme.AppBarOverlay">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="150dp"
                    android:background="#fff"
                    app:layout_scrollFlags="scroll">

                </LinearLayout>

                <android.support.design.widget.TabLayout
                    android:id="@+id/tablayout"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="#c0f9d0"
                    app:tabGravity="center"
                    app:tabIndicatorColor="@color/colorAccent"
                    app:tabMode="scrollable"
                    app:tabSelectedTextColor="@color/colorPrimaryDark"
                    app:tabTextColor="@color/colorPrimary" />

            </android.support.design.widget.AppBarLayout>

            <android.support.v4.view.ViewPager
                android:id="@+id/viewPager"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_behavior="@string/appbar_scrolling_view_behavior" />

        </android.support.design.widget.CoordinatorLayout>
    </com.yan.pullrefreshlayout.PullRefreshLayout>

</LinearLayout>`

**Comment by genius158** [comment]
由xml看，prl作为顶级视图，会最先处理touch事件，要做到你想要的效果，参考具体demo增加滑动判定，当然你可以考虑把prl放到CoordinatorLayout内部

**Comment by genius158** [comment]
参考 https://github.com/genius158/PullRefreshLayout/blob/developer/app/src/main/java/com/yan/refreshloadlayouttest/testactivity/ScrollingActivity.java
