### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by mnock** [genius158/PullRefreshLayout#24]
整个viewpager 下拉刷新支持吗

**Comment by genius158** [comment]
需要给PullRefreshLayout设置一个target 或者 用isTargetAbleScrollUp和isTargetAbleScrollDown添加更复杂的控制， 让它 知道 什么时候可以触发下拉刷新或上拉加载
至于 包裹 给什么 控件 ，其实 都无所谓

**Comment by genius158** [comment]
参考 https://github.com/genius158/PullRefreshLayout/blob/developer/app/src/main/java/com/yan/refreshloadlayouttest/testactivity/CommonActivity5.java
