### ISSUE TITLE
触摸事件处理有BUG

### ISSUE THREAD

**Issue by SCBoyChina** [genius158/PullRefreshLayout#25]
当刷新视图已经展开停留（刷新停留），如果给内部视图设置了长按监听，这个时候向上拖动内部视图会触发长按监听，应该是传递后的坐标一直没有怎么变化，导致触发了长按监听。如果是向下拖动是没问题的，传递后的坐标有增长所以不会触发长按监听。作者可以考虑处理下这种场景。

**Comment by genius158** [comment]
en 这个问题处理起来 有点麻烦
 嵌套 模式下 没有这个问题

**Comment by SCBoyChina** [comment]
@genius158 那这个问题有规划进行处理吗，虽然触发这个问题的概率还是比较低的。

**Comment by genius158** [comment]
看这个周末 或者 下个 周末吧

**Comment by genius158** [comment]
@SCBoyChina  已经提交到了master 分支 你可以拉下来 试试，应该没有问题了

**Comment by SCBoyChina** [comment]
@genius158  的确修复了，只是偶尔会出现拖动回顶部后内容视图无法滚动，但问题不大。另外我发现嵌套滚动时触发手势后，刷新视图没有像关闭嵌套滚动时是先收起刷新视图再传递手势，而是一起滚动，我看了下代码应该是onNestedPreFling的时候直接透传了加速度的原因，不知道是故意这么设计的吗还是遗漏了，运行起来效果的确不错，就是感觉命名有点乱。

**Comment by genius158** [comment]
嵌套模式下和SwipeRefreshLayout手势是一样的，没有其他的控制。
命名乱，是因为这个项目是我实习阶段就开始写的，还属于菜鸟级别，都是跟着感觉走~~

**Comment by SCBoyChina** [comment]
@genius158 个人感觉应该统一手势体验可能好一点，否则可能感觉有点割裂了。另外如果有空其实可以重构下，我看项目是有个分支是3.0的，是否可以考虑重构下，统一命名，更加规范优雅点，这样项目应该能帮助到更多的人，好的项目应该让更多的人了解分享使用。当然前提是你有时间，😁😁😁
