### ISSUE TITLE
使用单纯的回弹实现仿IOS回弹效果有点问题

### ISSUE THREAD

**Issue by yuxuelian** [genius158/PullRefreshLayout#26]
下拉回弹的时候下拉到一定距离松手后开始执行回弹动画,正在执行动画期间如果再次进行下拉,动画停止执行,并且内部的View无法跟随手指继续下滑,上拉的时候拉动到一定距离松手后,开始执行回弹动画,如果再次上拉,回弹动画停止执行了,但是View也不会跟随手指继续上滑动,试了试Demo也是有这个问题,Demo里边的那个单纯的回弹案例  里边左边是ListView  右边是RecyclerView   ListView貌似没有这个问题,RecyclerView有这个问题,我也是包裹的RecyclerView,就会无法滑动

**Comment by genius158** [comment]
@yuxuelian 本项目demo，我无法重现你说的问题~

**Comment by yuxuelian** [comment]
你多试试   肯定有滑动的情况   往上滑一些再松手   然后立马再去滑  就滑不动了    这种情况只出现在实现了NestedScrollingChild 的View上   比如RecyclerView跟NestedScrollView都会出现滑动的情况

**Comment by yuxuelian** [comment]
> @yuxuelian 本项目demo，我无法重现你说的问题~

你多试试 肯定有滑不动的情况 往上滑一些再松手 然后立马再去滑 就滑不动了 这种情况只出现在实现了NestedScrollingChild 的View上 比如RecyclerView跟NestedScrollView都会出现滑不动的情况
