### ISSUE TITLE
这个Layout跟Activity滑动返回一起使用时   这个会有冲突   滑动返回失效

### ISSUE THREAD

**Issue by yuxuelian** [genius158/PullRefreshLayout#29]
不知道是你这个库的问题还是滑动返回库的问题 肯定是事件拦截没做好

**Comment by yuxuelian** [comment]
不知道是你这个库的问题还是滑动返回库的问题   肯定是事件拦截没做好

**Comment by genius158** [comment]
我试了一下 并没有问题 参考https://github.com/genius158/PullRefreshLayout/blob/master/app/src/main/java/com/yan/refreshloadlayouttest/testactivity/CommonActivity1.java
