### ISSUE TITLE
关于首页上拉不能没有回弹效果

### ISSUE THREAD

**Issue by pjh520** [genius158/PullRefreshLayout#3]
在测试中发现，如果PullRefreshLayout嵌套的linearlayout中的子view总的高度超过一个屏幕的高度，那么上拉回弹效果将不会出现，如果有此类需求，有什么好的解决方案吗？

**Comment by genius158** [comment]
@pjh520 用一个scrollView 套在外面~

**Comment by pjh520** [comment]
@genius158 已经嵌套了 
![3](https://user-images.githubusercontent.com/12854050/30016776-0ba87d3e-9189-11e7-8ff8-06fcbaae14e6.png)

**Comment by genius158** [comment]
![qq 20170904155806](https://user-images.githubusercontent.com/17870843/30016971-e1be9160-9189-11e7-8a2c-c52b959c7d6b.png)

可以的呀

**Comment by genius158** [comment]
@pjh520  你 说的 上拉 回弹 是？？  加载 更多  那个？？？

**Comment by pjh520** [comment]
@genius158 不是，就是简单的上拉回弹，不能加载更多。你的prl_loadMoreEnable这个属性设置为false

**Comment by genius158** [comment]
@pjh520 回滑 缓冲？

**Comment by pjh520** [comment]
@genius158 是的 ，但是好像不行  你看下demo中OptionActivity，就是了 子view的高度超过一个屏幕，回弹效果就没了

**Comment by genius158** [comment]
@pjh520 设计上就是 子view 可滑动的 回滑 滑动交给子view ， 不能滑动再 回弹  。 其实 你那种是 我最早的设计 感觉不是 很友好 ，有需要的 话 后面 考虑 再  加回去~

**Comment by pjh520** [comment]
@genius158 因为现在很多界面，比如个人中心页面，基本上都是一个scrollview嵌套linearlayout，然后linearlayout中有许多子view，这些子view的总高度到后期基本上超过一个屏幕。

**Comment by pjh520** [comment]
@genius158 有必要建个群，这样交流比较方便

**Comment by genius158** [comment]
这个库 第一次 提交 是 4个月之前 ，到现在 也许 都 没有几个人 真正在用，建一个群 应该 也没多少人加，
真的有必要吗。。。

**Comment by pjh520** [comment]
@genius158 只要库使用方便，没什么大问题，慢慢会有人用的，今天在掘金上面看到，对比最近比较火的smartRefreshlayout,感觉一个刷新库，集成的东西多了，就杂了。不然加下我的QQ：1031028399
