### ISSUE TITLE
CoordinatorLayout包裹ViewPager事件冲突

### ISSUE THREAD

**Issue by nanguaSky** [genius158/PullRefreshLayout#30]
<?xml version="1.0" encoding="utf-8"?>
<com.yan.pullrefreshlayout.PullRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/refreshLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:prl_headerShowGravity="follow"
    app:prl_twinkEnable="false">

    <android.support.design.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.design.widget.AppBarLayout
            android:id="@+id/appBarLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:elevation="0dp">

            <android.support.design.widget.CollapsingToolbarLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_scrollFlags="scroll|exitUntilCollapsed">

                <include layout="@layout/header_deal_home" />

                <android.support.v7.widget.Toolbar
                    android:id="@+id/toolbar"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:paddingStart="0dp"
                    android:paddingEnd="0dp"
                    app:contentInsetStart="0dp"
                    app:layout_anchor="@id/placeholder"
                    app:layout_anchorGravity="center"
                    app:layout_collapseMode="pin">

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="center_vertical"
                        android:orientation="horizontal">

                        <TextView
                            android:id="@+id/tv_search"
                            android:layout_width="0dp"
                            android:layout_height="34dp"
                            android:layout_marginStart="@dimen/margin_medium"
                            android:layout_marginTop="16dp"
                            android:layout_marginBottom="16dp"
                            android:layout_weight="1"
                            android:background="@drawable/shape_white_oval"
                            android:drawableEnd="@drawable/icon_main_search"
                            android:drawablePadding="7dp"
                            android:gravity="center_vertical"
                            android:paddingStart="@dimen/margin_medium"
                            android:paddingEnd="@dimen/margin_medium"
                            android:text="搜索所需内容，如抖音粉丝，头条号"
                            android:textColor="@color/color_5B6285"
                            android:textSize="12sp"
                            android:visibility="invisible"
                            tools:visibility="visible" />

                        <ImageView
                            android:id="@+id/iv_issuedeal"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:padding="@dimen/margin_medium"
                            android:src="@drawable/icon_deal_home_issue" />

                    </LinearLayout>

                </android.support.v7.widget.Toolbar>

            </android.support.design.widget.CollapsingToolbarLayout>

            <FrameLayout
                android:id="@+id/fl_tab"
                android:layout_width="match_parent"
                android:layout_height="60dp">

                <com.flyco.tablayout.SlidingTabLayout
                    android:id="@+id/pss_tab"
                    android:layout_width="match_parent"
                    android:layout_height="60dp"
                    android:background="@drawable/pic_home_switchbg"
                    android:paddingTop="10dp"
                    app:tl_indicator_color="@color/colorAccent"
                    app:tl_indicator_corner_radius="3dp"
                    app:tl_indicator_height="3dp"
                    app:tl_indicator_margin_bottom="7dp"
                    app:tl_indicator_width="25dp"
                    app:tl_tab_space_equal="true"
                    app:tl_textBold="BOTH"
                    app:tl_textSelectColor="@color/text_color_333"
                    app:tl_textUnselectColor="@color/color_989CB3"
                    app:tl_textsize="17sp" />

            </FrameLayout>

        </android.support.design.widget.AppBarLayout>

        <android.support.v4.view.ViewPager
            android:id="@+id/viewPager"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior" />

        <ViewStub
            android:id="@+id/vs_gift"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            android:layout_gravity="bottom|end"
            android:layout_marginEnd="10dp"
            android:layout_marginBottom="10dp"
            android:layout="@layout/pop_novice_gift" />

    </android.support.design.widget.CoordinatorLayout>

</com.yan.pullrefreshlayout.PullRefreshLayout>

**Comment by nanguaSky** [comment]
ViewPager里面的页面只是recyclerView列表，现在出现的情况是，上拉的时候，CollapsingToolbarLayout折叠了头部， 当我下啦的时候，直接触发了下拉刷新，它并没有等待我的CollapsingToolbarLayout展开头部就提前触发了下拉刷新

**Comment by genius158** [comment]
参考

**Comment by genius158** [comment]
需要处理滑动冲突，参考https://github.com/genius158/PullRefreshLayout/blob/master/app/src/main/java/com/yan/refreshloadlayouttest/testactivity/ScrollingActivity.java

**Comment by nanguaSky** [comment]
很抱歉，没有注释所以没注意到那段监听代码
