### ISSUE TITLE
PathsDrawable 华为mate 10青春版不显示

### ISSUE THREAD

**Issue by inshyma** [genius158/PullRefreshLayout#31]
使用PathsDrawable 在华为mate 10青春版手机上不显示
android version 9.1

**Comment by genius158** [comment]
本库为手势库，应该不会导致绘制问题，移除本库，确定正常吗？

**Comment by inshyma** [comment]
我同样问题也问了 SmartRefreshLayout 的作者scwang90  回复是"PathsDrawable 不兼容 android P，这个问题目前没有找到解决方案"  然后我找到了一个PathDrawable库 : https://github.com/pskink/PathDrawable
