### ISSUE TITLE
【建议】上拉和下拉时碰到的小尴尬

### ISSUE THREAD

**Issue by RamboPan** [genius158/PullRefreshLayout#32]
就这样使用的时候发现设置了之后还是能够上拉与下拉。
```javascript
refreshLayout.setRefreshEnable(false);
refreshLayout.setLoadMoreEnable(false);
```

我开始以为是我的问题，然后在你的 demo 中试了下也不行。
```javascript
public class NestedFragment extends Fragment {
    ……
    private void initRefreshLayout(View container) {
        refreshLayout = (PullRefreshLayout) container.findViewById(R.id.refreshLayout);

        refreshLayout.setLoadTriggerDistance((int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 60, getResources().getDisplayMetrics()));
        refreshLayout.setFooterView(classicLoadView = new ClassicHoldLoadView(getContext(), refreshLayout));
        refreshLayout.setOnRefreshListener(……);
        //在这使用
        refreshLayout.setRefreshEnable(false);
        refreshLayout.setLoadMoreEnable(false);
    }
}
```
查看你的代码，发现了如果 pullTwinkEnable 是 true ，不管上下拉是否为 false，那么还是能够上下拉，如果我设置为 false ，那么上拉下拉就禁止了。
```javascript
我感觉你的思路是：
可以单纯设置允许上下拉，不触发加载。
（setTwinkEnable = true , setRefreshEnable = false, setLoadMoreEnable = false）
也可以设置为上下拉并加载 
( 都为 true )；
或者设置为禁止上下拉 
( 都为 false )。
```
如果按这样的话，我试了上下拉不触发加载的情况，上拉加载更多仍然触发加载，下拉刷新不触发刷新 …… 感觉上拉下拉被区别对待了，不太统一。

个人第一次看到 setEnable 这种感觉应该是总开关，没想到还要 setTwinkEnable 才能关 …… 
如果老哥下次还要写控件的话，能不能开关只写一个。😂

**Comment by RamboPan** [comment]
才写完这个我又发现了一个情况，我是想上拉加载更多，没数据时，停止上拉加载，然后自己加一个到底提示，按说应该这样调（因为单独调setLoadMoreEnable(false）还是能上拉。

setLoadMoreEnable(false);
setTwinkEnable(false);

这样我下拉刷新时又不行了。。。
我理解的是，刷新时可以一直刷的，尽管没有新数据。但是加载到尽头时一般有个提示，这时应该禁止上拉。

我是没有没有找到正确的单独开关姿势么 ？😶

**Comment by genius158** [comment]
@RamboPan 感谢你对这个项目的关注，
首先，这个项目最开始只是为了回弹实现ios的效果而存在，之后有了其他的需求，才加上TwinkEnable来禁止回弹，添加刷新，加载，加载只是为了与刷新成对才做的，实际上项目中并没有它的用武之地，setAutoLoadingEnable 相对有点用
所以回弹是这个项目的核心，至于要实现单边不可上来或下拉参考Tab FunGames，
加载完成（没有更多）提示 dome apk 第一个就有样例，加载更多建议还是写在adapter里

**Comment by RamboPan** [comment]
@genius158
我看了那个 Tab FunGames 的代码部分，发现可以用这个思路。
通过调整 maxDistance 与 triggerDistance 的数值，来实现
- 禁止上拉
- 可以上拉但是不触发加载
- 或者上拉也触发加载
三种情况。上下拉、回弹 默认设为 enable 就行。😂

加载更多写在 adapter 中 ？这个好像没有明白意思。🤔

**Comment by genius158** [comment]
一般要加载更多的都是listview 或者recyclerview，加载更多主要还是用他们的adapter实现

**Comment by RamboPan** [comment]
嗯，懂你意思了，暂时没问题了，谢谢了。

**Comment by LukeChow** [comment]
我也遇到这个问题了，我折腾了半天最后是在onLoading回调里直接loadMoreComplete然后return的。。。
