### ISSUE TITLE
如何主动关闭二楼

### ISSUE THREAD

**Issue by wushange** [genius158/PullRefreshLayout#35]
作者框架很好， 很轻量和很大扩展性， 在用你的框架实现类似微信首页下拉显示小程序窗口， 基本功能已经上线 下拉展开上拉关闭， 都没问题， 目前项目需求要在二楼加一个按钮 主动关闭二楼， 我试着调用 refreshComplete() 方法 页面倒是恢复了 不过无法在触发下拉状态， 我debug了一下 看是在refreshComplete后再次下拉后状态一直是正在刷新 无法触发再次刷新， 请问有什么解决办法呢 3Q

**Comment by genius158** [comment]
非常抱歉，github没有给我任何这条消息的反馈，以至于我现在才看到你发的问题，demo里有一个二级刷新的例子，可以用这个调试看看，如果还需要的话~~
