### ISSUE TITLE
autoRefresh(false)不生效

### ISSUE THREAD

**Issue by kitencx** [genius158/PullRefreshLayout#36]
下拉刷新后触发了刷新行为，UI的刷新状态由viewModel中的LiveData控制，这时候会再次调用autoRefresh(false)去将试图置为刷新状态，由于下方代码导致false无效而产生无限回调
https://github.com/genius158/PullRefreshLayout/blob/8b2af1f4dba946ef3567a371b5e72575c347ffed/pullrefreshlayout/src/main/java/com/yan/pullrefreshlayout/PullRefreshLayout.java#L726-L739
在refreshWithAction赋值前进行了回调

**Comment by genius158** [comment]
是说刷新过程中，再次调用 autoRefresh(false) 执行会嵌套? 
我没测试出来
