### ISSUE TITLE
关于仿支付宝下拉的问题

### ISSUE THREAD

**Issue by KafukaChen** [genius158/PullRefreshLayout#5]
小哥你好，我现在实现了仿支付宝首页的下拉刷新效果，但是发现该项目中recyclerview有默认回弹效果（就是拉到底依然可以上拉防守回弹），现在我想屏蔽这个效果，prl.setMoveWithFooter(false);prl.setMoveWithHeader(false);这两个方法不管用，prl.setMoveWithContent(false);就直接没有了仿支付宝首页下拉刷新的效果，请指教有什么方法。还有一个问题，下方的recyclerview条目的第一个点击事件消失了

**Comment by genius158** [comment]
@KafukaChen 完全仿支付宝 你可以 把回弹(setTwinkEnable )去了看看
到哪个位置 不想它移动 你可以 自己 控制 位置( moveChildren)

prl.setMoveWithFooter(false);prl.setMoveWithHeader(false);prl.setMoveWithContent(false);  
这些是控制跟随移动的，具体api很多(滑动方向，滑动位置，阻止事件～)，都好控制，可以看看例子
关于点击事件，你是用的Demo改的嘛？ 理论上应该是没有这个问题的～

**Comment by KafukaChen** [comment]
谢谢小哥，setTwinkEnable 的确有用，设置有效；第二个问题是我自己的原因

**Comment by genius158** [comment]
@KafukaChen 好的，感谢支持～
