### ISSUE TITLE
上拉加载更多时候如果慢慢的上滑，加载footer经常只显示一半。

### ISSUE THREAD

**Issue by greatflag** [genius158/PullRefreshLayout#6]

**Comment by genius158** [comment]
@greatflag 如果已经处于加载状态，footer显示多少跟滑动惯性有关

**Comment by genius158** [comment]
@greatflag 或者刷新过程还没有结束

**Comment by guoyoujin** [comment]
效果很棒，试了下，发现下拉刷新中，先向上滚动隐藏刷新控件，在用力向下滚动的时候，发现刷新控件是显示不全的，没有完全滚动到最顶部

**Comment by genius158** [comment]
@guoyoujin 是的 效果就是这么设计的，走的回弹效果，有不合理吗？

**Comment by guoyoujin** [comment]
@genius158 感觉最好是当正在刷新的时候，先滚动到刷新的最顶部，在执行弹性滚动，这样效果应该能更好些。你觉得呢

**Comment by genius158** [comment]
@guoyoujin 关于这部分，qq也是也我这么处理的，暂时还不准备调整

**Comment by genius158** [comment]
@guoyoujin 正在项目中刷新其实是很快的，没多少机会，会接触到这个效果
