### ISSUE TITLE
控件显示问题

### ISSUE THREAD

**Issue by chenshena** [genius158/PullRefreshLayout#7]
![3](https://user-images.githubusercontent.com/28971712/32083568-489119d6-baf6-11e7-8887-b7ca0ad31425.png)
didi_head 布局改成layout_height =wrap_conent，显示成
![1](https://user-images.githubusercontent.com/28971712/32083595-8005e838-baf6-11e7-9b39-0cca0ff590a8.jpg)
改成固定的layout_height为固定值375dp 显示成
![2](https://user-images.githubusercontent.com/28971712/32083624-ad0b4d14-baf6-11e7-99c2-a8d01c28473d.jpg)
这要如何处理

**Comment by genius158** [comment]
@chenshena demo的顶部距离是根据fiexdtop的高度设置的，
确认一下你的布局

**Comment by chenshena** [comment]
这个高度 是不是要固定某个值，不能wrap_content

**Comment by genius158** [comment]
@chenshena 没有吧 你可以随便放一个textview试一试，如果header布局变动不太大的话

**Comment by genius158** [comment]
@chenshena demo 就是warp呀
