### ISSUE TITLE
demo项目写的很乱，文档很乱。各种设置也太乱了，而且容易冲突不起作用。

### ISSUE THREAD

**Issue by q805699513** [genius158/PullRefreshLayout#8]
阻尼效果还不错。

**Comment by genius158** [comment]
@q805699513 demo很乱个人认为是命名的问题，
文档确实只标明了功能，没其他作用，
prl的方法是比较多，刚接触可能是会觉得很乱，试着都用用就好了。
最后这个库并非拿来就能用（回弹效果除外），是有一点门槛的（需要自行自定义header和footer），可能也就让很多人没了兴趣，用的人应该也不会多，所以细节也就没有过多处理。

**Comment by q805699513** [comment]
@genius158 举个例子吧，比如你那个设置成app:prl_pullUpMaxDistance设置成0，其实是想不用其中一种的阻尼效果。但是你的设置成0内部是等于这个的高度的。还是我在你的demo里第三个还是第四个activity里关闭loadmore并没起作用，后面又注释了一些框架设置代码，还崩溃了。

**Comment by q805699513** [comment]
@genius158 您的框架整体效果是不错的，最好有一种风格，可以让用户用少量代码就能实现该风格下拉刷新功能（比如类似QQ）。现在感觉你demo布局xml文件里写的属性比较多，虽然加强了自定义功能展示。但是会导致用户不知道是否该去掉这个属性。导致xml代码增多。

**Comment by genius158** [comment]
@q805699513 本库是主回弹库，暂时没有提供单边不可回弹的设置，参考WithoutTwinkFooter.java

**Comment by genius158** [comment]
@q805699513 xml部分全部写那么多只是是为了复制张贴到文档部分，可以全部去掉，
如果不想触发加载更多的方法loadmore 关闭 的同时也要关闭autoloadiing（默认是都关闭的），回弹效果是无法去除的

**Comment by genius158** [comment]
@q805699513 也感谢你的提议，后面会处理一下
