### ISSUE TITLE
二级刷新，Header如何修改高度

### ISSUE THREAD

**Issue by ltfy100** [genius158/PullRefreshLayout#9]
RT

**Comment by genius158** [comment]
简单的话可以用 refreshLayout.setPullUpMaxDistance(0);和refreshLayout.setPullDownMaxDistance(0)来控制，当然也可以用提供的事件事件处理的几个方法来做，判断会多一点，
dome里的header高度大多是直接在代码里设置的，或是适应header的布局的高度的

**Comment by ltfy100** [comment]
3Q
